HOME_BASE = 5781

STAT_MAP = {
    'passatt': HOME_BASE,
    'comp': HOME_BASE + 1,
    'passtd': HOME_BASE + 2,
    'passint': HOME_BASE + 3,
    'passyards_start': HOME_BASE + 4,
    'passyards_stop': HOME_BASE + 6,
    'rusat': HOME_BASE + 6,
    'rusyds_start': HOME_BASE + 7,
    'rusyds_stop': HOME_BASE + 9,
    'rustd': HOME_BASE + 9,
    'rec': HOME_BASE - 15,
    'rectd': HOME_BASE - 12,
    'recyds_start': HOME_BASE - 14,
    'recyds_stop': HOME_BASE - 12,
    'kr': HOME_BASE - 11,
    'kryds_start': HOME_BASE - 10,
    'kryds_stop': HOME_BASE - 8,
    'krtd': HOME_BASE - 8,
    'pr': HOME_BASE - 7,
    'pryds_start': HOME_BASE - 6,
    'pryds_stop': HOME_BASE - 4,
    'prtd': HOME_BASE - 4,
    'xpa': 6016,
    'xpm': 6017,
    'fga': 6018,
    'fgm': 6019,
}